# - id: autosonoff-off
#   alias: Sonoff http command
#   trigger:
#     platform: time
#     seconds: 30
#   action:
#   - service: shell_command.fix_sonoff_4
- id: autosonoff-off
  alias: 'Sonoff Fix'
  initial_state: 'on'
  hide_entity: True
  trigger:
    platform: time
    seconds: 30
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/garage/power4
      payload: 'OFF'

- id: fix-sonoff
  alias: 'Power state on HA start-up'
  initial_state: 'on'
  hide_entity: True
  trigger:
    platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/garage/power1
      payload: ''
  - service: mqtt.publish
    data:
      topic: cmnd/garage/power2
      payload: ''
  - service: mqtt.publish
    data:
      topic: cmnd/garage/power3
      payload: ''
  - service: mqtt.publish
    data:
      topic: cmnd/garage/power4
      payload: ''

- id: notify_garage_apertura
  alias: '[Notifica] Notifica Apertura Garage'
  initial_state: 'on'
  hide_entity: True
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0001fd6296
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      message: Saracinesca aperta
    service: notify.ios_ilendrius
- id: notify_garage_chiusura
  alias: '[Notifica] Notifica Chiusura Garage'
  initial_state: 'on'
  hide_entity: True
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0001fd6296
    from: 'on'
    platform: state
    to: 'off'
  action:
  - data:
      message: Saracinesca chiusa
    service: notify.ios_ilendrius
      
- id: notify_ingresso_apertura
  alias: '[Notifica] Notifica Apertura Ingresso'
  initial_state: 'on'
  hide_entity: True
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d000112031b
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      message: Ingresso aperto
    service: notify.ios_ilendrius
- id: notify_ingresso_chiusura
  alias: '[Notifica] Notifica Chiusura Ingresso'
  initial_state: 'on'
  hide_entity: True
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d000112031b
    from: 'on'
    platform: state
    to: 'off'
  action:
  - data:
      message: Ingresso chiuso
    service: notify.ios_ilendrius
- id: comodino_andrea_on_off
  alias: '[Stanza da letto] Comodino Andrea On/Off'
  initial_state: 'on'
  trigger:
  - event_data:
      click_type: single
      entity_id: binary_sensor.switch_158d00012641b4
    event_type: click
    platform: event
  action:
  - data:
      entity_id: light.comodino_andrea
    entity_id: light.comodino_andrea
    service: light.toggle
- id: comodino_andrea_bright
  alias: '[Stanza da letto] Comodino Andrea Bright'
  initial_state: 'on'
  trigger:
  - event_data:
      click_type: long_click_press
      entity_id: binary_sensor.switch_158d00012641b4
    event_type: click
    platform: event
  action:
  - data: {}
    data_template:
      brightness: '{% set suggested = states.light.comodino_andrea.attributes.brightness|int
        + 31 %} {% if suggested < 200 %} {{ suggested }} {% else %} 200 {% endif %}

        '
    entity_id: light.comodino_andrea
    service: light.turn_on
- id: comodino_andrea_dim
  alias: '[Stanza da letto] Comodino Andrea Dim'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: click
    event_data:
      click_type: double
      entity_id: binary_sensor.switch_158d00012641b4
  action:
    service: light.turn_on
    entity_id: light.comodino_andrea
    data_template:
      brightness: '{% set suggested = states.light.comodino_andrea.attributes.brightness|int
        - 50 %} {% if suggested > 25 %} {{ suggested }} {% else %} 25 {% endif %}

        '
- id: comodino_eleonora_on_off
  alias: '[Stanza da letto] Comodino Eleonora On/Off'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00013ecb24
      click_type: single
  action:
    service: light.toggle
    entity_id: light.comodino_ele
- id: comodino_eleonora_bright
  initial_state: 'on'
  trigger:
    platform: event
    event_type: click
    event_data:
      click_type: long_click_press
      entity_id: binary_sensor.switch_158d00013ecb24
  action:
    service: light.turn_on
    entity_id: light.comodino_ele
    data_template:
      brightness: '{% set suggested = states.light.comodino_ele.attributes.brightness|int
        + 31 %} {% if suggested < 200 %} {{ suggested }} {% else %} 200 {% endif %}

        '
- id: comodino_eleonora_dim
  alias: '[Stanza da letto] Comodino Eleonora Dim'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: click
    event_data:
      click_type: double
      entity_id: binary_sensor.switch_158d00013ecb24
  action:
    service: light.turn_on
    entity_id: light.comodino_ele
    data_template:
      brightness: '{% set suggested = states.light.comodino_ele.attributes.brightness|int
        - 50 %} {% if suggested > 25 %} {{ suggested }} {% else %} 25 {% endif %}

        '
- id: accendi_neon_interni_garage_auto
  alias: '[Garage] Neon Interni On Movimento'
  initial_state: 'on'
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d00010f7fda
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      entity_id: switch.sonoff_garage_1
    service: switch.turn_on
  condition:
  - condition: state
    entity_id: binary_sensor.door_window_sensor_158d0001fd6296
    state: 'on'
  - after: '18:00'
    before: '12:00'
    condition: time
# - id: accendi_neon_esterno_garage_auto
#   alias: '[Garage] Neon Esterno On Movimento'
#   trigger:
#   - entity_id: binary_sensor.motion_sensor_158d00010f7fda
#     from: 'off'
#     platform: state
#     to: 'on'
#   action:
#   - data:
#       entity_id: switch.sonoff_garage_2
#     service: switch.turn_on
#   condition:
#   - condition: state
#     entity_id: binary_sensor.door_window_sensor_158d0001fd6296
#     state: 'on'
#   - after: '20:00'
#     before: 07:00
#     condition: time
- id: notifica_garage
  alias: '[Notifica] Notifica Movimento Garage'
  initial_state: 'on'
  hide_entity: True
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d00010f7fda
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      message: Movimento rilevato in garage
    service: notify.ios_ilendrius
  condition:
- id: spegni_garage_auto
  alias: '[Garage] Timer Off (2 minuti)'
  initial_state: 'on'
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d00010f7fda
    for:
      seconds: 30
    from: 'on'
    platform: state
    to: 'off'
  action:
  - data:
      entity_id: switch.sonoff_garage_1
    service: switch.turn_off
  - data:
      entity_id: switch.sonoff_garage_2
    service: switch.turn_off
  condition:
  - condition: state
    entity_id: binary_sensor.door_window_sensor_158d0001fd6296
    state: 'off'
- id: dispensa_on
  alias: '[Dispenza] Lampadario On'
  initial_state: 'on'
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d00013fede0
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      entity_id: light.lampadario_dispensa
    service: light.turn_on
- id: dispensa_off
  alias: '[Dispenza] Lampadario Off'
  initial_state: 'on'
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d00013fede0
    from: 'on'
    platform: state
    to: 'off'
  action:
  - entity_id: light.lampadario_dispensa
    service: light.turn_off
- id: dispensa_on_off
  alias: '[Dispenza] On/Off'
  initial_state: 'on'
  trigger:
  - event_data:
      click_type: single
      entity_id: binary_sensor.switch_158d00013f84db
    event_type: click
    platform: event
  action:
  - data:
      entity_id: light.lampadario_dispensa
    entity_id: light.lampadario_dispensa
    service: light.toggle
- id: alarm_armed_away
  alias: '[Allarme] Modalità Assente attivata'
  initial_state: 'on'
  hide_entity: True
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: armed_away
  action:
  - data:
      message: Modalità Assente attivata
    data_template:
      message: L'allarme di casa è stato attivato in modalità Assente. Arrivederci
      title: Modalità Assente attivata
    service: notify.ios_ilendrius
- id: alarm_armed_home
  alias: '[Allarme] Modalità A Casa attivata'
  initial_state: 'on'
  hide_entity: True
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: armed_home
  action:
  - data:
      message: Modalità A Casa attivata
    data_template:
      message: L'allarme di casa è stato attivato in modalità A Casa. Buonanotte
      title: Modalità a casa attivata
    service: notify.ios_ilendrius
- id: alarm_arming_away
  alias: '[Allarme] Attivando Modalità Assente'
  initial_state: 'on'
  hide_entity: True
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: pending
  action:
  - data:
      message: Sto attivando l'allarme di casa, assicurati che le porte e le finestre
        siano chiuse
    service: notify.ios_ilendrius
- id: alarm_disarmed
  alias: '[Allarme] Disarmato'
  initial_state: 'on'
  hide_entity: True
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: disarmed
  action:
  - service: notify.ios_ilendrius
    data:
      message: Allarme Disabled
  - service: switch.turn_off
    entity_id: switch.siren_switch
  - data:
      message: The house alarm has been Deactivated
    service: notify.ios_ilendrius
- id: alarm_triggered
  alias: '[Allarme] Scattato'
  initial_state: 'on'
  hide_entity: True
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: triggered
  action:
  - service: switch.turn_on
    entity_id: switch.siren_switch
  - service: notify.ios_ilendrius
    data:
      message: ALLARME SCATTATO!!! {{ states[states.alarm_control_panel.house.attributes.changed_by.split(".")[0]][
        states.alarm_control_panel.house.attributes.changed_by.split(".")[1]].name
        }}
- id: alarm_warning
  alias: '[Allarme] Attenzione'
  initial_state: 'on'
  hide_entity: True
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: warning
  action:
  - service: notify.ios_ilendrius
    data:
      message: ALLARME Attenzione {{ states[states.alarm_control_panel.house.attributes.changed_by.split(".")[0]][
        states.alarm_control_panel.house.attributes.changed_by.split(".")[1]].name
        }}
  - data:
      message: Hello, the house alarm has been tripped. Please deactivate
    service: notify.ios_ilendrius
- id: accendi_balcone
  alias: '[Balcone Interno] Accendi Lampione'
  initial_state: 'on'
  hide_entity: True
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d000201980a
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      brightness: 150
      entity_id: light.balcone_interno
    service: light.turn_on
  condition:
  - after: '18:00'
    before: '7:00'
    condition: time
- id: spegni_balcone
  alias: '[Balcone Interno] Spegni Lampione'
  initial_state: 'on'
  hide_entity: True
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d000201980a
    from: 'on'
    platform: state
    to: 'off'
  action:
  - data:
      entity_id: light.balcone_interno
    service: light.turn_off
- id: imposta_sala_da_pranzo
  alias: 'Scene sala da pranzo'
  initial_state: 'on'
  hide_entity: True
  trigger:
    platform: state
    entity_id: input_select.sala_da_pranzo
  action:
    service: script.turn_on
    entity_id: script.input_select_sala_da_pranzo_script
- id: imposta_soggiorno
  alias: 'Scene soggiorno'
  initial_state: 'on'
  hide_entity: True
  trigger:
    platform: state
    entity_id: input_select.soggiorno
  action:
    service: script.turn_on
    entity_id: script.input_select_soggiorno_script
