# Sonoff Fix Temporaneo
- id: autosonoff-off
  alias: 'Sonoff Fix'
  initial_state: 'on'
  hide_entity: False
  trigger:
    platform: time
    seconds: 30
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/garage/power4
      payload: 'OFF'

# Sonoff Fix from Hass.io
- id: fix-sonoff
  alias: 'Power state on HA start-up'
  initial_state: 'on'
  hide_entity: True
  trigger:
    platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/garage/power1
      payload: ''
  - service: mqtt.publish
    data:
      topic: cmnd/garage/power2
      payload: ''
  - service: mqtt.publish
    data:
      topic: cmnd/garage/power3
      payload: ''
  - service: mqtt.publish
    data:
      topic: cmnd/garage/power4
      payload: ''


# Ingresso Notifiche     
- id: notify_ingresso_apertura
  alias: '[Notifica] Notifica Apertura Ingresso'
  initial_state: 'on'
  hide_entity: True
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d000112031b
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      message: Ingresso aperto
    service: notify.ios_ilendrius
- id: notify_ingresso_chiusura
  alias: '[Notifica] Notifica Chiusura Ingresso'
  initial_state: 'on'
  hide_entity: True
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d000112031b
    from: 'on'
    platform: state
    to: 'off'
  action:
  - data:
      message: Ingresso chiuso
    service: notify.ios_ilendrius
    
# Camera da Letto Trigger
- id: comodino_andrea_on_off
  alias: '[Stanza da letto] Comodino Andrea On/Off'
  initial_state: 'on'
  trigger:
  - event_data:
      click_type: single
      entity_id: binary_sensor.switch_158d00012641b4
    event_type: click
    platform: event
  action:
  - data:
      entity_id: light.comodino_andrea
    entity_id: light.comodino_andrea
    service: light.toggle
- id: comodino_andrea_bright
  alias: '[Stanza da letto] Comodino Andrea Bright'
  initial_state: 'on'
  trigger:
  - event_data:
      click_type: long_click_press
      entity_id: binary_sensor.switch_158d00012641b4
    event_type: click
    platform: event
  action:
  - data: {}
    data_template:
      brightness: '{% set suggested = states.light.comodino_andrea.attributes.brightness|int
        + 31 %} {% if suggested < 200 %} {{ suggested }} {% else %} 200 {% endif %}

        '
    entity_id: light.comodino_andrea
    service: light.turn_on
- id: comodino_andrea_dim
  alias: '[Stanza da letto] Comodino Andrea Dim'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: click
    event_data:
      click_type: double
      entity_id: binary_sensor.switch_158d00012641b4
  action:
    service: light.turn_on
    entity_id: light.comodino_andrea
    data_template:
      brightness: '{% set suggested = states.light.comodino_andrea.attributes.brightness|int
        - 50 %} {% if suggested > 25 %} {{ suggested }} {% else %} 25 {% endif %}

        '
- id: comodino_eleonora_on_off
  alias: '[Stanza da letto] Comodino Eleonora On/Off'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00013ecb24
      click_type: single
  action:
    service: light.toggle
    entity_id: light.comodino_ele
- id: comodino_eleonora_bright
  alias: '[Stanza da letto] Comodino Eleonora Bright'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: click
    event_data:
      click_type: long_click_press
      entity_id: binary_sensor.switch_158d00013ecb24
  action:
    service: light.turn_on
    entity_id: light.comodino_ele
    data_template:
      brightness: '{% set suggested = states.light.comodino_ele.attributes.brightness|int
        + 31 %} {% if suggested < 200 %} {{ suggested }} {% else %} 200 {% endif %}

        '
- id: comodino_eleonora_dim
  alias: '[Stanza da letto] Comodino Eleonora Dim'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: click
    event_data:
      click_type: double
      entity_id: binary_sensor.switch_158d00013ecb24
  action:
    service: light.turn_on
    entity_id: light.comodino_ele
    data_template:
      brightness: '{% set suggested = states.light.comodino_ele.attributes.brightness|int
        - 50 %} {% if suggested > 25 %} {{ suggested }} {% else %} 25 {% endif %}

        '

# Garage Trigger
- id: accendi_neon_interni_garage_auto
  alias: '[Garage] Neon Interni On Movimento'
  initial_state: 'on'
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d00010f7fda
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      entity_id: switch.sonoff_garage_1
    service: switch.turn_on
  condition:
  - condition: state
    entity_id: binary_sensor.door_window_sensor_158d0001fd6296
    state: 'on'
  - after: '18:00'
    before: '12:00'
    condition: time
- id: spegni_garage_auto
  alias: '[Garage] Timer Off (1 minuto)'
  initial_state: 'on'
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d00010f7fda
    for:
      seconds: 60
    from: 'on'
    platform: state
    to: 'off'
  action:
  - data:
      entity_id: switch.sonoff_garage_1
    service: switch.turn_off
  - data:
      entity_id: switch.sonoff_garage_2
    service: switch.turn_off
  condition:
  - condition: state
    entity_id: binary_sensor.door_window_sensor_158d0001fd6296
    state: 'off'

# Garage Notifiche
- id: notifica_garage
  alias: '[Notifica] Notifica Movimento Garage'
  initial_state: 'on'
  hide_entity: True
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d00010f7fda
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      message: Movimento rilevato in garage
    service: notify.ios_ilendrius
  condition:
- id: notify_garage_apertura
  alias: '[Notifica] Notifica Apertura Garage'
  initial_state: 'on'
  hide_entity: True
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0001fd6296
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      message: Saracinesca aperta
    service: notify.ios_ilendrius
- id: notify_garage_chiusura
  alias: '[Notifica] Notifica Chiusura Garage'
  initial_state: 'on'
  hide_entity: True
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0001fd6296
    from: 'on'
    platform: state
    to: 'off'
  action:
  - data:
      message: Saracinesca chiusa
    service: notify.ios_ilendrius

# Dispenza Trigger
- id: dispensa_on
  alias: '[Dispenza] Lampadario On'
  initial_state: 'on'
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d00013fede0
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      entity_id: light.lampadario_dispensa
    service: light.turn_on
- id: dispensa_off
  alias: '[Dispenza] Lampadario Off'
  initial_state: 'on'
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d00013fede0
    from: 'on'
    platform: state
    to: 'off'
  action:
  - entity_id: light.lampadario_dispensa
    service: light.turn_off
- id: dispensa_on_off
  alias: '[Dispenza] On/Off con Sensore Porta'
  initial_state: 'on'
  trigger:
  - event_data:
      click_type: single
      entity_id: binary_sensor.switch_158d00013f84db
    event_type: click
    platform: event
  action:
  - data:
      entity_id: light.lampadario_dispensa
    entity_id: light.lampadario_dispensa
    service: light.toggle


# Balcone Interno Trigger
- id: accendi_balcone
  alias: '[Balcone Interno] Accendi Lampione'
  initial_state: 'on'
  hide_entity: True
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d000201980a
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      brightness: 150
      entity_id: light.balcone_interno
    service: light.turn_on
  condition:
  - after: '18:00'
    before: '7:00'
    condition: time
- id: spegni_balcone
  alias: '[Balcone Interno] Spegni Lampione dopo 10 secondi'
  initial_state: 'on'
  hide_entity: True
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d000201980a
    for:
      seconds: 10
    from: 'on'
    platform: state
    to: 'off'
  action:
  - data:
      entity_id: light.balcone_interno
    service: light.turn_off


# Allarme Trigger
- id: trigger-home
  alias: '[Allarme] Scatta allarme quando attivo A Casa'
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d000112031b
      to: 'on'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0001b95bf4
      to: 'on'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d000201980a
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.house
      state: armed_home
  action:
    service: xiaomi_aqara.play_ringtone
    data:
      gw_mac: !secret xiaomi_mac
      ringtone_id: 2
      ringtone_vol: 100
- id: trigger-away
  alias: '[Allarme] Scatta allarme quando Attivo'
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d000112031b
      to: 'on'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0001b95bf4
      to: 'on'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d000201980a
      to: 'on'
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d00010f7fda
      to: 'on'
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001e5413e
      to: 'on'
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001e5764c
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.house
      state: armed_away
  action:
  - service: xiaomi_aqara.play_ringtone
    data:
      gw_mac: !secret xiaomi_mac
      ringtone_id: 2
      ringtone_vol: 8


# Allarme Notifiche
- id: alarm_armed_away
  alias: '[Notifica] Modalità Assente attivata'
  initial_state: 'on'
  hide_entity: True
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: armed_away
  action:
    data_template:
      message: 'Allarme di casa è stato attivato in modalità Assente. Arrivederci'
      title: 'Allarme'
    service: notify.ios_ilendrius
# - id: alarm_armed_home
#   alias: '[Allarme] Modalità A Casa attivata'
#   initial_state: 'on'
#   hide_entity: True
#   trigger:
#   - platform: state
#     entity_id: alarm_control_panel.house
#     to: armed_home
#   action:
#     data_template:
#       title: 'Allarme'
#       message: 'Allarme di casa è stato attivato in modalità A Casa. Buonanotte'
#   - service: notify.ios_ilendrius
- id: alarm_arming_away
  alias: '[Notifica] Attivando Modalità Assente'
  initial_state: 'on'
  hide_entity: True
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: pending
  action:
  - service: notify.ios_ilendrius
    data_template:
      title: 'Allarme'
      message: 'Sto attivando allarme di casa, assicurati che le porte e le finestre siano chiuse'
  - service: xiaomi_aqara.play_ringtone
    data:
      gw_mac: !secret xiaomi_mac
      ringtone_id: 2
      ringtone_vol: 2
- id: alarm_disarmed
  alias: '[Notifica] Disarmato'
  initial_state: 'on'
  hide_entity: True
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: disarmed
  action:
  - data_template:
      title: 'Allarme'
      message: 'Allarme di casa disattivato.'
    service: notify.ios_ilendrius
- id: alarm_triggered
  alias: '[Allarme] Scattato'
  initial_state: 'on'
  hide_entity: True
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: triggered
  action:
  - service: switch.turn_on
    entity_id: switch.siren_switch
  - service: notify.ios_ilendrius
    data_template:
      title: 'Allarme'
      message: 'Scattato! {{ states[states.alarm_control_panel.house.attributes.changed_by.split(".")[0]][
        states.alarm_control_panel.house.attributes.changed_by.split(".")[1]].name
        }}'
- id: alarm_warning
  alias: '[Notifica] Attenzione'
  initial_state: 'on'
  hide_entity: True
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: warning
  action:
  - service: notify.ios_ilendrius
    data:
      title: 'Allarme'
      message: 'Attenzione {{ states[states.alarm_control_panel.house.attributes.changed_by.split(".")[0]][
        states.alarm_control_panel.house.attributes.changed_by.split(".")[1]].name
        }}'

# Slider
- id: 'Soggiorno-brightness-slider'
  alias: 'Soggiorno Light - Adjust Brightness'
  trigger:
    platform: state
    entity_id: input_number.soggiorno_brightness
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.soggiorno
        brightness: "{{ trigger.to_state.state | int }}"

- id: 'Sala-da-pranzo-brightness-slider'
  alias: 'Sala da pranzo Light - Adjust Brightness'
  trigger:
    platform: state
    entity_id: input_number.sala_da_pranzo_brightness
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.sala_da_pranzo
        brightness: "{{ trigger.to_state.state | int }}"


# Select
- id: imposta_sala_da_pranzo
  alias: 'Scene sala da pranzo'
  initial_state: 'on'
  hide_entity: True
  trigger:
    platform: state
    entity_id: input_select.sala_da_pranzo_preset
  action:
    service: hue.hue_activate_scene
    data_template:
      group_name: 'Sala da pranzo'
      scene_name: '{{ trigger.to_state.state }}'
- id: imposta_soggiorno
  alias: 'Scene soggiorno'
  initial_state: 'on'
  hide_entity: True
  trigger:
    platform: state
    entity_id: input_select.soggiorno_preset
  action:
    service: hue.hue_activate_scene
    data_template:
      group_name: 'Soggiorno'
      scene_name: '{{ trigger.to_state.state }}'
