homeassistant: !include config/homeassistant.yaml
frontend: !include config/frontend.yaml
http: !include config/http.yaml
updater:
discovery:
conversation:
config:
sun:
history: !include data/history.yaml
logbook: !include data/logbook.yaml
sensor: !include_dir_merge_list sensor/
binary_sensor: !include_dir_merge_list binary_sensor/
tts: !include config/tts.yaml
mqtt: !include config/mqtt.yaml
light: !include_dir_merge_list lights/
hue: !include config/hue.yaml
netatmo: !include config/netatmo.yaml
apcupsd: !include config/apcupsd.yaml
device_tracker: !include config/device_tracker.yaml
homekit: !include config/homekit.yaml
media_player: !include config/media_player.yaml
group: !include_dir_merge_named group
zone: !include config/zone.yaml
xiaomi_aqara: !include config/xiaomi_aqara.yaml
ios: !include config/ios.yaml
ifttt: !include config/ifttt.yaml
automation: !include automations.yaml
automation old: !include automations_old.yaml
alarm_control_panel: !include alarm.yaml
panel_custom: !include panel_custom.yaml
script: !include_dir_merge_named script
switch: !include_dir_merge_list switch
cover: !include config/cover.yaml
input_boolean: !include config/input_boolean.yaml
input_number: !include config/input_number.yaml
input_select: !include config/input_select.yaml
weather: !include config/weather.yaml
variable: !include config/variable.yaml
scene: !include config/scene.yaml
recorder: !include config/recorder.yaml
cloud: !include config/cloud.yaml
notify: !include config/notify.yaml
zwave: !include config/zwave.yaml
customizer:
  custom_ui: local
  hide_attributes:
    - node_id
    - value_index