homeassistant:
  # Name of the location where Home Assistant is running
  name: Casa
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Rome

  customize: !include customize.yaml
  packages: !include_dir_named packages

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  javascript_version: es5
#   panel_iframe:
#     nodered:
#       title: 'Node-Red'
#       icon: 'mdi:shuffle-variant'
#       url: 'http://mastropino.homepc.it:1880'
  themes:
    PmxMononight:
      # MyVariables
      base-hue: '220' #Controls the base (and accent) color hue (0-360) | 0=Red 60=Yellow 120=Green 180=Cyan 240=Blue 300=Magenta 360=Red
      base-sat: '16%' #Controls the saturation of the theme (0%-100%) | 0%=Grey 100%=Full Saturation
      # MyVar
      huesat: 'var(--base-hue), var(--base-sat),'
      # Primary Color
      primary-color: 'hsl(var(--huesat) 20%)'
      # Backgrounds
      primary-background-color: 'var(--primary-color)'
      secondary-background-color: 'hsl(var(--huesat) 16%)'
      paper-listbox-background-color: 'var(--primary-color)'
      paper-card-background-color: 'hsl(var(--huesat) 12%)'
      paper-dialog-background-color: 'var(--paper-card-background-color)'
      table-row-background-color: 'hsl(var(--huesat) 12%)'
      table-row-alternative-background-color: 'hsl(var(--huesat) 10%)'
      # Devider
      divider-color: 'hsla(0, 0%, 0%, 0)'
      dark-divider-opacity: '0'
      light-divider-opacity: '0'
      # Text colors
      primary-text-color: 'hsl(var(--huesat) 60%)'
      text-primary-color: 'hsl(var(--huesat) 60%)'
      secondary-text-color: 'hsl(var(--huesat) 60%)'
      disabled-text-color: 'hsl(var(--huesat) 70%)'
      sidebar-text_-_color: 'hsl(var(--huesat) 90%)'
      sidebar-text-color: 'hsl(var(--huesat) 90%)'
      paper-card-header-color: 'hsl(var(--base-hue), 90%, 50%)'
      # Text Adjustments
      paper-font-headline_-_letter-spacing: '-0.5px'
      paper-font-headline_-_font-weight: '500'
      paper-font-body1_-_font-weight: '500'
      # Nav Menu
      paper-listbox-color: 'hsl(var(--huesat) 50%)'
      paper-grey-50: 'hsl(var(--huesat) 50%)'
      paper-grey-200: 'hsla(var(--huesat) 26%)'
      # Paper card
      paper-item-icon-color: 'hsl(var(--huesat) 30%)'
      paper-item-icon-active-color: 'var(--paper-item-icon-color)'
      paper-item-icon_-_color: 'var(--paper-item-icon-color)'
      paper-item-selected_-_background-color: 'hsla(0, 0%, 0%, 0.2)'
      paper-tabs-selection-bar-color: 'hsla(0, 0%, 0%, 0.2)'
      # Labels
      label-badge-red: 'hsla(0, 0%, 0%, 0)'
      label-badge-border-color: 'var(--label-badge-red)'
      label-badge-background-color: 'var(--paper-card-background-color)'
      label-badge-text-color: 'var(--primary-text-color)'
      # Shadows
      shadow-elevation-2dp_-_box-shadow: 'inset 0px 0px 0px 4px hsl(var(--huesat) 18%)'
      shadow-elevation-16dp_-_box-shadow: 'inset 0px 0px 0px 4px hsl(var(--huesat) 28%)'
      # Switches
      paper-toggle-button-checked-button-color: 'hsl(var(--base-hue), 90%, 50%)'
      paper-toggle-button-checked-bar-color: 'hsl(var(--huesat) 25%)'
      paper-toggle-button-unchecked-button-color: 'hsl(var(--huesat) 25%)'
      paper-toggle-button-unchecked-bar-color: 'hsl(var(--huesat) 5%)'
      # Sliders
      paper-slider-knob-color:  'hsl(var(--base-hue), 90%, 50%)'
      paper-slider-knob-start-color: 'hsl(var(--base-hue), 80%, 25%)'
      paper-slider-pin-color:  'hsl(var(--base-hue), 90%, 50%)'
      paper-slider-active-color:  'hsl(var(--base-hue), 90%, 50%)'
      paper-slider-container-color: 'hsl(var(--huesat) 28%)'
      paper-slider-secondary-color: 'hsl(var(--huesat) 90%)'
      paper-slider-disabled-active-color: 'hsl(var(--base-hue), 80%, 25%)'
      paper-slider-disabled-secondary-color: 'hsl(var(--base-hue), 80%, 25%)'
      paper-dialog-color: 'hsl(var(--base-hue), 20%, 80%)'
#   router:
#     title: 'Router'
#     icon: 'mdi:router-wireless'
#     url: 'http://192.168.0.1'

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret home_password
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret home_url
#   ssl_certificate: /ssl/fullchain.pem
#   ssl_key: /ssl/privkey.pem

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:
  use_include_order: True
  include:
    domains:
      - sensor
      - climate
      - switch
      - media_player
  exclude:
    domains:
      - automation
      - weblink
      - updater

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor: !include_dir_merge_list sensor/

binary_sensor: !include_dir_merge_list binary_sensor/

# Text to speech
tts:
  platform: google
  language: 'it'

#MQTT
mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password
  protocol: 3.1
  discovery: true
  discovery_prefix: homeassistant
  birth_message:
    topic: "tele/hass1/LWT"
    payload: "Online"
    qos: 1
    retain: true
  will_message:
    topic: "tele/hass1/LWT"
    payload: "Offline"
    qos: 1
    retain: true

# Lights
light: !include_dir_merge_list lights/
hue:
  bridges:
    - host: !secret hue_host
      allow_hue_groups: true

# Netatmo entry
netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_username
  password: !secret netatmo_password

apcupsd:
  host: localhost

# Presence detector
device_tracker:
  - platform: nmap_tracker
    hosts: 
      - 192.168.0.60
      - 192.168.0.62
    consider_home: 50
    track_new_devices: true
  - platform: ping
    hosts:
      hostone: 192.168.0.62

# Media Player
media_player:
  - platform: webostv
    host: 192.168.0.20
    turn_on_action:
      service: media_player.turn_on
      entity_id: media_player.lg_webos_smart_tv

# Groups
group: !include_dir_merge_named group

# Zone
zone 2:
  name: Lavoro
  latitude: !secret work_latitude
  longitude: !secret work_longitude
  radius: 50
  icon: mdi:worker

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_key

config:

ios: #ios component

ifttt:
  key: !secret ifttt_key

automation: !include automations.yaml

alarm_control_panel: !include alarm.yaml
panel_custom: !include panel_custom.yaml

# Script
script: !include_dir_merge_named script

input_select:
  sala_da_pranzo_preset:
    options:
      - Relax
      - Lettura
      - Concentrazione
      - Energia
  soggiorno_preset:
    options:
      - Relax
      - Lettura
      - Concentrazione
      - Energia
 
switch: 
  - platform: mqtt
    name: "Sonoff Garage 1"
    command_topic: "cmnd/garage/power1"
    state_topic: "stat/garage/POWER1"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
  - platform: mqtt
    name: "Sonoff Garage 2"
    command_topic: "cmnd/garage/power2"
    state_topic: "stat/garage/POWER2"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
  - platform: mqtt
    name: "Sonoff Garage 3"
    command_topic: "cmnd/garage/power3"
    state_topic: "stat/garage/POWER3"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
  - platform: mqtt
    name: "Sonoff Garage 4"
    state_topic: "stat/garage/POWER4"
    command_topic: "cmnd/garage/power4"
    qos: 0
    optimistic: false
    retain: true
    payload_on: "ON"
    payload_off: "OFF"
    
cover:
#   - platform: mqtt
#     state_topic: "stat/garage/POWER4"
#     command_topic: "cmnd/garage/power4"
#     name: "Saracinesca"
#     qos: 0
#     retain: false
#     payload_open: "ON"
#     payload_close: "ON"
#     payload_stop: "ON"
#     state_open: "ON"
#     state_closed: "OFF"
#     optimistic: false
  - platform: template
    covers:
      saracinesca:
        friendly_name: "Saracinesca"
        value_template: >-
          {% if is_state('binary_sensor.door_window_sensor_158d0001fd6296', 'on') %}
            open
          {% else %}
            closed
          {% endif %}
        open_cover:
          service: script.attivagarage
        close_cover:
          service: script.attivagarage
        stop_cover:
          service: script.attivagarage
        icon_template: >-
          {% if is_state('binary_sensor.door_window_sensor_158d0001fd6296', 'on') %}
            mdi:garage-open
          {% else %}
            mdi:garage
          {% endif %}
          
shell_command:
  fix_sonoff_4: bash '/config/shell_command/fix-gaposa.sh'