homeassistant:
  name: Casa
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Rome
  customize: !include config/customize.yaml
  packages: !include_dir_named packages
  customize_glob: !include config/customize_glob.yaml
frontend:
  themes: !include_dir_merge_named themes/
  javascript_version: latest
  extra_html_url:
    - /local/custom_ui/custom-weather-card.html
  extra_html_url_es5:
    - /local/custom_ui/custom-weather-card.html
http:
  api_password: !secret home_password
  base_url: !secret home_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  cors_allowed_origins: !secret cors_allowed_origins
updater:
discovery:
conversation:
history: !include data/history.yaml
logbook: !include data/logbook.yaml
sun:
sensor: !include_dir_merge_list sensor/
binary_sensor: !include_dir_merge_list binary_sensor/
tts:
  platform: google
  language: 'it'
mqtt: !include config/mqtt.yaml
light: !include_dir_merge_list lights/
hue:
  bridges:
    - host: !secret hue_host
      allow_hue_groups: true
netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_username
  password: !secret netatmo_password
apcupsd:
  host: localhost
device_tracker: !include config/device_tracker.yaml
homekit: !include config/homekit.yaml
media_player: !include_dir_merge_list media_player/
group: !include_dir_merge_named group
zone 2:
  name: Lavoro
  latitude: !secret work_latitude
  longitude: !secret work_longitude
  radius: 50
  icon: mdi:worker
xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_key
config:
ios: !include config/ios.yaml
google_assistant: !include config/google_assistant.yaml
ifttt:
  key: !secret ifttt_key
automation: !include automations.yaml
automation old: !include automations_old.yaml
alarm_control_panel: !include alarm.yaml
panel_custom: !include panel_custom.yaml
script: !include_dir_merge_named script
input_select: !include_dir_merge_named input_select
switch: !include_dir_merge_list switch
cover: !include config/cover.yaml
input_number: !include_dir_merge_named input_number
input_boolean:
  weather:
customizer:
  custom_ui: local
weather:
  - platform: yweather
variable:  
  last_motion:
    value: 'Sconosciuto'
    restore: true
    attributes:
      icon: mdi:map-marker
      name: "Ultimo Movimento"
