homeassistant:
  # Name of the location where Home Assistant is running
  name: Casa
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Rome

  customize: !include customize.yaml
  packages: !include_dir_named packages

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  javascript_version: es5
  themes: !include_dir_merge_named themes/
#   panel_iframe:
#     nodered:
#       title: 'Node-Red'
#       icon: 'mdi:shuffle-variant'
#       url: 'http://mastropino.homepc.it:1880'
#   router:
#     title: 'Router'
#     icon: 'mdi:router-wireless'
#     url: 'http://192.168.0.1'

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret home_password
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret home_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:
  use_include_order: True
  include:
    domains:
      - sensor
      - climate
      - switch
      - media_player
  exclude:
    domains:
      - automation
      - weblink
      - updater

# View all events in a logbook
logbook:
  include:
    domains:
      - sensor
      - switch
      - media_player
      - cover
      - light
  exclude:
    domains:
      - automation
    entities:
      - automation.sonoff_http_command

# Track the sun
sun:

# Weather Prediction
sensor: !include_dir_merge_list sensor/

binary_sensor: !include_dir_merge_list binary_sensor/

# Text to speech
tts:
  platform: google
  language: 'it'

#MQTT
mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password
  protocol: 3.1
  discovery: true
  discovery_prefix: homeassistant
  birth_message:
    topic: "tele/hass1/LWT"
    payload: "Online"
    qos: 1
    retain: true
  will_message:
    topic: "tele/hass1/LWT"
    payload: "Offline"
    qos: 1
    retain: true

# Lights
light: !include_dir_merge_list lights/
hue:
  bridges:
    - host: !secret hue_host
      allow_hue_groups: true

# Netatmo entry
netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_username
  password: !secret netatmo_password

# APC
apcupsd:
  host: localhost

# Presence detector
device_tracker:
  - platform: nmap_tracker
    hosts: 
      - 192.168.0.60
      - 192.168.0.62
    consider_home: 50
    track_new_devices: true
  - platform: ping
    hosts:
      hostone: 192.168.0.62

homekit:
  pincode: '123-45-678'
  port: 51827

# Media Player
media_player: !include_dir_merge_list media_player/

# Groups
group: !include_dir_merge_named group

# Zone
zone 2:
  name: Lavoro
  latitude: !secret work_latitude
  longitude: !secret work_longitude
  radius: 50
  icon: mdi:worker

# Xiaomi Aqara
xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_key

# Confiuration Panel
config:

# iOS Component
ios:

#IFTT Component
ifttt:
  key: !secret ifttt_key

# Automations
automation: !include automations.yaml

# Alarm
alarm_control_panel: !include alarm.yaml
panel_custom: !include panel_custom.yaml

# Script
script: !include_dir_merge_named script

# Input
input_select:
  sala_da_pranzo_preset:
    options:
      - Relax
      - Lettura
      - Concentrazione
      - Energia
  soggiorno_preset:
    options:
      - Relax
      - Lettura
      - Concentrazione
      - Energia
  gateway_sound:
    name: Ringtone
    options: 
      - "0 - Police car 1"
      - "1 - Police car 2"
      - "2 - Accident"
      - "3 - Countdown"
      - "4 - Ghost"
      - "5 - Sniper rifle"
      - "6 - Battle"
      - "7 - Air raid"
      - "8 - Bark"
#      - "9 - None"
      - "10 - Doorbell"
      - "11 - Knock at a door"
      - "12 - Amuse"
      - "13 - Alarm clock"
#      - "14 - None"
#      - "15 - None"
#      - "16 - None"
#      - "17 - None"
#      - "18 - None"
#      - "19 - None"
      - "20 - MiMix"
      - "21 - Enthusiastic"
      - "22 - GuitarClassic"
      - "23 - IceWorldPiano"
      - "24 - LeisureTime"
      - "25 - ChildHood"
      - "26 - MorningStreamLiet"
      - "27 - MusicBox"
      - "28 - Orange"
      - "29 - Thinker"
      - "10001 - Alarm Sound 3"
      - "10002 - Beep 2x"
      - "10003 - Time beep 3x"
      - "10004 - Alarm Sound 1"
      - "10005 - Alarm Sound 2"
      - "10006 - Time beeps long"
    icon: mdi:music-note



input_boolean:
  mute_gateway_sounds:
    name: Mute
    icon: mdi:volume-off
# Switch
switch: !include_dir_merge_list switch

# Cover
cover: !include_dir_merge_list cover

### Input slider to control gateway volume ###
input_number:
  gateway_volume:
    name: Volume
    initial: 10
    min: 0
    max: 100
    step: 2
    icon: mdi:volume-high
### Input slider to control loop delay ###
  loop_delay:
    name: "Loop Delay"
    initial: 1
    min: 0
    max: 15
    step: 1
    icon: mdi:loop