- platform: mqtt
  name: "Sonoff Cucina"
  command_topic: "cmnd/cucina/power"
  state_topic: "stat/cucina/POWER"
  availability_topic: "tele/cucina/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false