"*.*":
  custom_ui_state_card: state-card-custom-ui
"light.*":
  show_last_changed: false
  state_card_mode: hide-slider
"switch.*":
  show_last_changed: true
"binary_sensor.*":
  show_last_changed: true
"sensor.*":
  show_last_changed: true
"automation.*":
  confirm_controls_show_lock: true
"input_boolean.weather":
  custom_ui_state_card: custom-weather-card
  friendly_name: Wetter
  config:
    weather: weather.yweather