group.default_view:
  order: '1'
group.lights:
  order: '2'
group.sensors:
  order: '3'
group.network:
  order: '4'
group.all_automations:
  hidden: false
  friendly_name: Tutte le automazioni
  order: '5'
group.light_balcone_interno:
  icon: mdi:cat
  order: '2'
group.light_cucina:
  icon: mdi:pot-mix
  order: '1'
group.light_soggiorno:
  icon: mdi:sofa
group.light_dispensa:
  icon: mdi:food-variant
group.light_sala_da_pranzo:
  icon: mdi:silverware-variant
group.light_garage:
  icon: mdi:garage
group.light_camera_da_letto:
  icon: mdi:hotel
group.light_bagno:
  icon: mdi:water-pump
group.light_bagnetto:
  icon: mdi:water-pump
group.stanze_home:
  order: '2'
group.weather:
  order: '5'
group.family:
  order: '1'
device_tracker.64bc0c807396:
  friendly_name: Ele
sun.sun:
  hidden: true
sensor.moon:
  hidden: true
sensor.dark_sky_summary:
  friendly_name: Meteo
sensor.dark_sky_apparent_temperature:
  friendly_name: Temperatura Percepita
sensor.dark_sky_humidity:
  friendly_name: Umidità
  icon: mdi:water-percent
sensor.dark_sky_temperature:
  friendly_name: Temperatura
  icon: mdi:temperature-celsius
sensor.dark_sky_precip_intensity:
  friendly_name: Intensità Precipitazioni
sensor.dark_sky_wind_speed:
  friendly_name: Velocità vento
sensor.dark_sky_daily_high_temperature:
  friendly_name: Temperatura Massima
sensor.dark_sky_daily_low_temperature:
  friendly_name: Temperatura Minima
light.abatjour_bianca:
  icon: mdi:lamp
light.abatjour_verde:
  icon: mdi:lamp
input_select.soggiorno_preset:
  friendly_name: Scene
light.gateway_light_f0b429cbef3f:
  icon: mdi:google-circles-extended
light.lampadario:
  icon: mdi:ceiling-light
light.lampadario_tv:
  icon: mdi:ceiling-light
sensor.humidity_158d00015b2df4:
  icon: mdi:water-percent
sensor.temperature_158d00015b2df4:
  icon: mdi:temperature-celsius
light.tepee:
  friendly_name: Tepee
  icon: mdi:tent
switch.tepee:
  friendly_name: Tepee
  icon: mdi:tent
light.fiore:
  icon: mdi:image-filter-vintage
media_player.lg_webos_smart_tv:
  icon: mdi:television
input_select.sala_da_pranzo_preset:
  friendly_name: Scene
light.lampadario_dispensa:
  icon: mdi:hololens
switch.sonoff_garage_1:
  friendly_name: Neon Interni
  icon: mdi:car-side
switch.sonoff_garage_2:
  friendly_name: Neon Esterno
  icon: mdi:white-balance-iridescent
switch.sonoff_garage_3:
  friendly_name: Neon Vespa
  icon: mdi:motorbike
#   entity_picture: /local/icons/vespa.svg
cover.saracinesca:
  device_class: garage
  friendly_name: Saracinesca
  show_last_changed: true
  order: '2'
binary_sensor.cube_158d0001051007:
  icon: mdi:cube-outline
light.comodino_ele:
  friendly_name: Comodino Eleonora
  icon: mdi:lamp
#   entity_picture: /local/icons/light.svg
light.comodino_andrea:
  friendly_name: Comodino Andrea
  icon: mdi:lamp
#   entity_picture: /local/icons/light.svg
group.sensor_ingresso:
  icon: mdi:login
sensor.illumination_158d0001e5764c:
  friendly_name: Luminosità Ingresso
sensor.ilendrius_battery_state:
  hidden: true
sensor.ilendrius_pro_battery_state:
  hidden: true
sensor.cpu_load_total:
  friendly_name: Carico CPU
sensor.memory_usage_real:
  friendly_name: Memoria Utilizzata
sensor.network_up:
  friendly_name: Upload
sensor.status_smart_sda:
  friendly_name: Status Smart Disco 1
sensor.status_smart_sdb:
  friendly_name: Status Smart Disco 2
sensor.total_size_volume_1:
  friendly_name: Spazio Totale
sensor.used_space_volume_1:
  friendly_name: Spazio Utilizzato
sensor.volume_used_volume_1:
  friendly_name: Occupato
sensor.temperature_158d0001e549e0:
  friendly_name: Temperatura Bagno
sensor.transmission_active_torrents:
  friendly_name: Torrent Attivi
sensor.transmission_down_speed:
  friendly_name: Velocità Download
  icon: mdi:download
sensor.transmission_up_speed:
  friendly_name: Velocità Upload
  icon: mdi:upload
sensor.processor_use:
  friendly_name: Utilizzo Processore
  icon: mdi:chip
script.check_sonoffs_version:
  friendly_name: Cerca aggiornamenti...
  icon: mdi:checkbox-multiple-marked-outline
script.update_sonoffs:
  friendly_name: Aggiorna Sonoffs
  icon: mdi:download-network
sensor.sonoff_4ch_pro_garage:
  icon: mdi:power-socket-eu
variable.last_motion:
  friendly_name: Stanza