- platform: nmap_tracker
  hosts: 
    - 192.168.0.60
    - 192.168.0.62
  consider_home: 100
  track_new_devices: true
- platform: ping
  hosts:
    ping_eleonora: 192.168.0.62
    ping_ilendrius: 192.168.0.60
- platform: owntracks
  max_gps_accuracy: 200
  waypoints: True
  mqtt_topic: "owntracks/#"
  events_only: True
  waypoint_whitelist:
    - hassio
# - platform: mqtt
#   devices:
#     ilendrius: owntracks/hassio/ilendrius
