port: 51827
entity_config:
  alarm_control_panel.house:
    code: !secret alarm_code
filter:
#     include_domains:
#       - alarm_control_panel
#       - light
#       - sensor
#       - cover
  include_entities:
    - alarm_control_panel.house
    - light.gateway_light_f0b429cbef3f
    - switch.tepee
    - light.comodino_ele
    - light.comodino_andrea
    - sensor.temperature_158d0001e549e0
    - sensor.temperature_158d00015b2df4
    - sensor.illumination_158d0001e515b8
    - sensor.illumination_158d0001e5764c
    - sensor.illumination_158d0001e5413e
    - sensor.illumination_158d0001e5156a
    - sensor.illumination_158d0001e514df
    - sensor.illumination_158d0001e51489
    - sensor.illumination_158d0001e513a8
    - sensor.humidity_158d0001e549e0
    - sensor.humidity_158d00015b2df4
    - sensor.pressure_158d0001e549e0
    - sensor.pressure_158d00015b2df4
    # Movimento Ingresso
    - binary_sensor.motion_sensor_158d0001e5764c
    # Movimento Sala da Pranzo
    - binary_sensor.motion_sensor_158d0001e5413e
    # Movimento Corridoio
    - binary_sensor.motion_sensor_158d0001e514df
    # Movimento Camera Armadi
    - binary_sensor.motion_sensor_158d0001e51489
    # Movimento Soggiorno
    - binary_sensor.motion_sensor_158d0001e513a8
    # Movimento Cucina
    - binary_sensor.motion_sensor_158d0001e515b8
    # Movimento Camera da Letto
    - binary_sensor.motion_sensor_158d0001e5156a
    # Movimento Garage
    - binary_sensor.motion_sensor_158d00010f7fda
    # Sensore Porta Ingresso
    - binary_sensor.door_window_sensor_158d000112031b
    # Sensore Finestra Stanza Armadio
    - binary_sensor.door_window_sensor_158d0001b95954
    # Finestra Cucina
    - binary_sensor.door_window_sensor_158d000201980a
    # Sensore Finestra Camera da Letto
    - binary_sensor.door_window_sensor_158d0001de6e16
    # Sensore Finestra a Ribalta Bagno
    - binary_sensor.door_window_sensor_158d0001e44493
    # Sensore Finestra a ribalta Bagnetto
    - binary_sensor.door_window_sensor_158d0001b95bf4
    # Sensore Saracinesca
    - binary_sensor.door_window_sensor_158d0001fd6296
#     exclude_entities:
#       - light.lampione
#       - light.lampadario
#       - light.lampadario_1
#       - light.lampadario_2
#       - light.lampadario_3
#       - light.lampadario_dispensa
#       - light.lampadario_tv
#       - light.fiore
#       - light.hue_go
#       - light.piantana
#       - light.abatjour_bianca
#       - light.abatjour_verde
#       - switch.sonoff_garage_1
#       - switch.sonoff_garage_2
#       - switch.sonoff_garage_3
#       - switch.sonoff_garage_4
#       - light.xmasactivegroupeven
#       - light.xmasactivegroupodd
#       - light.xmasactivegroup
#       - light.tepee
#       - light.stanza_da_letto
#       - light.soggiorno
#       - light.sala_da_pranzo
#       - light.garage
#       - light.entrata
#       - light.dispensa
#       - light.cucina
#       - light.corridoio
#       - light.bagno
#       - light.bagnetto
#       - light.balcone_interno
#       - light.area_di_intrattenimento_1
#     exclude_domains:
#       - script
#       - group
#       - sensor
#       - climate
#       - input_select
#       - input_number
#       - input_boolean

