auto_start: False
entity_config:
  alarm_control_panel.allarme:
    code: !secret alarm_code
  media_player.lg_webos_smart_tv:
    feature_list:
      - feature: on_off
      - feature: play_pause
#       - feature: play_stop
#       - feature: toggle_mute
  switch.tepee:
    type: outlet
filter:
  include_entities:
    - cover.saracinesca
    - switch.sonoff_garage_1
    - switch.sonoff_garage_2
    - switch.sonoff_garage_3
    - alarm_control_panel.allarme
    - light.gateway_light_f0b429cbef3f
    - switch.tepee
    - light.comodino_ele
    - light.comodino_andrea
    # Z-wave Specchio Bagno
    - switch.switch
    - sensor.temperature_158d0001e549e0
    - sensor.temperature_158d00015b2df4
    - sensor.illumination_158d0001e515b8
    - sensor.illumination_158d0001e5764c
    - sensor.illumination_158d0001e5413e
    - sensor.illumination_158d0001e5156a
    - sensor.illumination_158d0001e514df
    - sensor.illumination_158d0001e51489
    - sensor.illumination_158d0001e513a8
    - sensor.humidity_158d0001e549e0
    - sensor.humidity_158d00015b2df4
    - sensor.pressure_158d0001e549e0
    - sensor.pressure_158d00015b2df4
    # Movimento Ingresso
    - binary_sensor.motion_sensor_158d0001e5764c
    # Movimento Sala da Pranzo
    - binary_sensor.motion_sensor_158d0001e5413e
    # Movimento Corridoio
    - binary_sensor.motion_sensor_158d0001e514df
    # Movimento Camera Armadi
    - binary_sensor.motion_sensor_158d0001e51489
    # Movimento Soggiorno
    - binary_sensor.motion_sensor_158d0001e513a8
    # Movimento Cucina
    - binary_sensor.motion_sensor_158d0001e515b8
    # Movimento Camera da Letto
    - binary_sensor.motion_sensor_158d0001e5156a
    # Movimento Garage
    - binary_sensor.motion_sensor_158d00010f7fda
    # Sensore Porta Ingresso
    - binary_sensor.door_window_sensor_158d000112031b
    # Sensore Finestra 1 Sala da Pranzo
    - binary_sensor.door_window_sensor_158d0001b97da6
    # Sensore Finestra 2 Sala da Pranzo
    - binary_sensor.door_window_sensor_158d0001b7bce7
    # Sensore Finestra Stanza Armadio
    - binary_sensor.door_window_sensor_158d0001b95954
    # Finestra Cucina
    - binary_sensor.door_window_sensor_158d000201980a
    # Sensore Finestra Camera da Letto
    - binary_sensor.door_window_sensor_158d0001de6e16
    # Sensore Finestra a Ribalta Bagno
    - binary_sensor.door_window_sensor_158d0001e44493
    # Sensore Finestra a ribalta Bagnetto
    - binary_sensor.door_window_sensor_158d0001b95bf4
    # Sensore Porta Dispensa
    - binary_sensor.door_window_sensor_158d00013fede0
    # Finestra Soggiorno
    - binary_sensor.door_window_sensor_158d0001e44446
    - media_player.lg_webos_smart_tv