- platform: gearbest
  currency: EUR
  items:
    - url: https://www.gearbest.com/access-control/pp_626703.html
      name: Aqara Window Door Sensor
    - url: https://www.gearbest.com/alarm-systems/pp_659226.html
      name: Aqara Human Body Sensor
    - url: https://www.gearbest.com/access-control/pp_626702.html
      name: Aqara Temperature Humidity Sensor
    - url: https://www.gearbest.com/alarm-systems/pp_610095.html
      name: Aqara Smart Light Switch Wireless Version