- platform: systemmonitor
  resources:
  - type: disk_use_percent
    arg: /
  - type: memory_free
  - type: memory_use_percent
  - type: processor_use
  - type: since_last_boot
  - type: network_in
    arg: eth0
  - type: network_out
    arg: eth0